databases:
  - name: martin
    databaseName: martin
    user: martin
 
services:
  - type: web
    name: martin
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn web.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: martin
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.6
