# Generated by Django 3.2.7 on 2021-12-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo'),
        ),
    ]
